kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: {{ ocp_grafana_serviceaccount_name }}
    namespace: {{ ocp_thanos_project_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view