kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-querier-thanos
subjects:
  - kind: ServiceAccount
    name: thanos-querier-thanos
    namespace: {{ ocp_thanos_project_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-querier-thanos
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-querier-thanos
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - configmaps
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-receive
subjects:
  - kind: ServiceAccount
    name: thanos-receive
    namespace: {{ ocp_thanos_project_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-receive
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thanos-receive
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - configmaps