apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: {{ namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: "{{ lookup('template', './prometheus.yml') | from_yaml }}"
