version: "3.9"
services:
        mongo:
                image: mongo:latest
                environment:
                    - MONGO_INITDB_ROOT_USERNAME=root
                    - MONGO_INITDB_ROOT_PASSWORD=openliberty
                ports:
                    - "27017:27017"
                volumes:
                    - ~/mongo/data:/data/db
                    - "./assets/:/docker-entrypoint-initdb.d/"
                command: mongod
        leaderboard:
                build: ./leaderboard
                ports:
                        - "9080:9080"
        server:
                build: ./server
                ports:
                        - "9070:9080"
        client:
                build: ./client
                ports:
                        - "3000:3000"

