package io.openliberty.spacerover.game;

public enum GameServerState {
	SERVER_STARTED, GUI_CONNECTED, GESTURE_CONNECTED, GUI_AND_GESTURE_CONNECTED, LEADERBOARD_CONNECTED,
	ROVER_CONNECT_TEST, ROVER_CONNECTED, GAMEBOARD_CONNECT_TEST,
	ALL_CONNECTED, GAME_STARTED, GAME_ENDED, ERROR_OCCURRED;
}
