apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafanadatasource
  namespace: {{ ocp_thanos_project_name }}
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true 
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: "Bearer {{ ocp_grafana_serviceaccount_token.stdout }}"
      type: prometheus
      url: "https://thanos-querier.thanos.svc.cluster.local:9091"
  name: prometheus-grafanadatasource.yaml