apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ grafana_subscription }}
  namespace: {{ ocp_thanos_project_name }}
spec:
  channel: {{ grafana_channel }}
  name: {{ grafana }}
  source: {{ grafana_catalog_source }}
  sourceNamespace: {{ grafana_catalog_source_namespace }}
  installPlanApproval: Automatic