apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: client
  name: client
spec:
  type: LoadBalancer 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    app.service: client
status:
  loadBalancer: {}
