apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: openliberty
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: space-rover/mongo
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pvc-0
          # Change Pull Policy for Remote Registry
          imagePullPolicy: Never
      restartPolicy: Always
      volumes:
        - name: mongo-pvc-0
          persistentVolumeClaim:
            claimName: mongo-pvc-0
status: {}


