apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: prometheus
  name: prometheus
spec:
  type: LoadBalancer
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app.service: prometheus
status:
  loadBalancer: {}
