{
 "title": "Open Liberty Space Rover Mission Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of Games Played",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "application_totalNumberOfGames", "legendFormat": "Total number of games" },
    {
     "expr": "application_numberOfSuddenDeathGamesPlayed",
     "legendFormat": "Total number of sudden death games"
    },
    {
     "expr": "application_numberOfClassicGamesPlayed",
     "legendFormat": "Total number of classic games"
    },
    {
     "expr": "application_numberOfPlanetHopGamesPlayed",
     "legendFormat": "Total number of planet hop games"
    },
    {
     "expr": "application_numberOfGuidedGamesPlayed",
     "legendFormat": "Total number of guided games"
    }
   ]
  },
  {
   "title": "Average User Score",
   "type": "graph",
   "description": "The average final score per game played today.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_totalScore/application_totalNumberOfGames",
     "legendFormat": "Score"
    }
   ]
  },
  {
   "title": "Damage Taken Average",
   "type": "graph",
   "description": "The average amount of damage taken during games played today.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_totalDamage / application_totalNumberOfGames",
     "legendFormat": "Damage Average"
    }
   ]
  },
  {
   "title": "Average Game Length",
   "type": "graph",
   "description": "The average time it took to complete a game today.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_timeInGame_seconds/application_totalNumberOfGames",
     "legendFormat": "Game length seconds"
    }
   ]
  },
  {
   "title": "Rover Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Volts" }
   ],
   "targets": [
    { "expr": "application_voltageBattery" }
   ]
  },
  {
   "title": "Space Rover Battery Percentage",
   "type": "graph",
   "description": "The battery level percentage of the space rover. If the space rover isn't reporting the percentage, or is a wired model, this will show 100%. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_pctBatteryLevel_percent",
     "legendFormat": "Battery Percentage"
    }
   ]
  }
 ]
}