apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-test.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  type: NodePort
  ports:
    - name: "3000"
      nodePort: 31000
      port: 3000
      targetPort: 80
  selector:
    io.kompose.service: client
status:
  loadBalancer: {}
