apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-test.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mockrover
  name: mockrover
spec:
  ports:
    - name: "5045"
      port: 5045
      targetPort: 5045
  selector:
    io.kompose.service: mockrover
status:
  loadBalancer: {}
