apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-test.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mockrover
  name: mockrover
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mockrover
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-test.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mockrover
    spec:
      containers:
        - image: uhryniuk/mockrover
          name: mockrover
          ports:
            - containerPort: 5045
          resources: {}
      restartPolicy: Always
status: {}
