apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.service: grafana
        app.name: space-rover
    spec:
      containers:
        - image: space-rover/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
          securityContext:
            runAsUser: 1000
          # Change Pull Policy for Remote Registry
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
