apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: grafana
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - name: "3010"
      port: 3010
      targetPort: 3000
  selector:
    app.service: grafana
status:
  loadBalancer: {}
