---
- name: Generate Grafana Operator resources
  template:
    src: template/grafana-operator.yml
    dest: dest/grafana-operator.yml
- name: Create Grafana Operator
  shell: "oc apply -f dest/grafana-operator.yml"
- name: Wait for Grafana Operator
  shell: "oc get deployments grafana-operator-controller-manager -n {{ ocp_thanos_project_name }} -o jsonpath='{ .status.conditions[?(@.type==\"Available\")].status }'"
  register: grafana
  until: grafana.stdout.find('True') != -1
  retries: 10
- name: Generate Grafana
  template:
    src: template/grafana.yml
    dest: dest/grafana.yml
- name: Delete Grafana service account (if exists)
  shell: "oc delete sa {{ ocp_grafana_serviceaccount_name }} -n {{ ocp_thanos_project_name }} || exit 0"
- name: Create Grafana service account
  shell: "oc create sa {{ ocp_grafana_serviceaccount_name }} -n {{ ocp_thanos_project_name }}"
- name: Add cluster-monitoring-view to Grafana service account
  shell: "oc adm policy add-role-to-user cluster-monitoring-view -z {{ ocp_grafana_serviceaccount_name }} -n {{ ocp_thanos_project_name }}"
- name: Generate Grafana ClusterRoleBinding
  template:
    src: template/grafana-clusterrolebinding.yml
    dest: dest/grafana-clusterrolebinding.yml
- name: Create cluster-monitoring-view ClusterRoleBinding
  shell: "oc apply -f dest/grafana-clusterrolebinding.yml"
- name: Generate token
  shell: "oc create token {{ ocp_grafana_serviceaccount_name }} --duration=8760h -n {{ ocp_thanos_project_name }}" 
  register: ocp_grafana_serviceaccount_token
- name: Generate Grafana datasource
  template:
    src: template/grafana-data-source.yml
    dest: dest/grafana-data-source.yml
- name: Cleanup Grafana metadata
  shell: "oc delete -f dest/grafana.yml || exit 0"
- name: Cleanup Grafana Data Source metadata
  shell: "oc delete -f dest/grafana-data-source.yml || exit 0"
- name: Add OCP Grafana dashboards
  shell: "oc apply -f dashboards/ -n {{ ocp_thanos_project_name }}"
- name: Add Grafana
  shell: "oc apply -f dest/grafana.yml"
- name: Add Grafana data source
  shell: "oc apply -f dest/grafana-data-source.yml"
- name: Wait for Grafana
  shell: "oc get grafana example-grafana -n {{ ocp_thanos_project_name }} -o jsonpath='{.status.phase}'"
  register: grafanainstance
  until: grafanainstance.stdout.find('reconciling') != -1
  retries: 20