---
- name: Generate Grafana Operator resources
  template:
    src: template/grafana-operator.yml
    dest: dest/grafana-operator.yml
- name: Create Grafana Operator
  shell: "oc apply -f dest/grafana-operator.yml"
- name: Generate Grafana
  template:
    src: template/grafana.yml
    dest: dest/grafana.yml
- name: Delete Grafana service account (if exists)
  shell: "oc delete sa {{ ocp_grafana_serviceaccount_name }}"
  ignore_errors: yes
- name: Create Grafana service account
  shell: "oc create sa {{ ocp_grafana_serviceaccount_name }}"
- name: Add cluster-monitoring-view to Grafana service account
  shell: "oc adm policy add-role-to-user cluster-monitoring-view -z {{ ocp_grafana_serviceaccount_name }}"
- name: Generate token
  shell: "oc create token {{ ocp_grafana_serviceaccount_name }} --duration=8760h -n {{ ocp_thanos_project_name }}" 
  register: ocp_grafana_serviceaccount_token
- name: Generate Grafana datasource
  template:
    src: template/grafana-data-source.yml
    dest: dest/grafana-data-source.yml
- name: Cleanup Grafana metadata
  shell: "oc delete -f dest/grafana.yml"
  ignore_errors: yes
- name: Cleanup Grafana Data Source metadata
  shell: "oc delete -f dest/grafana-data-source.yml"
  ignore_errors: yes
- name: Add OCP Grafana dashboards
  shell: "oc apply -f dashboards/"
- name: Add Grafana
  shell: "oc apply -f dest/grafana.yml"
- name: Add Grafana data source
  shell: "oc apply -f dest/grafana-data-source.yml"