---
  - name: Build Command Center 
    hosts: localhost
    connection: local 
    tasks:
      - name: Login to OCP
        include_tasks:
          file: tasks/ocp_login.yml
      - name: Create project namespaces
        include_tasks:
          file: tasks/create_namespaces.yml
      - name: Create operators
        include_tasks:
          file: tasks/create_operators.yml
      - name: Configure Strimzi Operator
        include_tasks:
          file: tasks/configure_strimzi.yml
      - name: Configure Grafana Operator
        include_tasks:
          file: tasks/configure_grafana.yml
      - name: Configure OpenLiberty Operator
        include_tasks:
          file: tasks/configure_openliberty.yml
      - name: Configure Thanos Store Gateway, Receive, and Querier
        include_tasks:
          file: tasks/configure_thanos.yml
      # - name: Build and Push All Space Rover Images
      #   include_tasks:
      #     file: tasks/build_and_push_all.yml
      # - name: Create OpenLibertyApplications
      #   include_tasks:
      #     file: tasks/create-openlibertyapplications.yml
      - name: Display Cluster Information
        debug:
          msg: 
            - "Grafana URL: {{ ocp_grafana_route.stdout }}"
            - "Grafana Username: {{ ocp_grafana_username.stdout }}"
            - "Grafana Password: {{ ocp_grafana_password.stdout }}"
            - "Kafka Cluster URL: {{ kafka_cluster_url.stdout }}"
            - "Thanos Querier URL: https://{{ ocp_thanos_querier_url.stdout }}"
            - "Thanos Receive URL: https://{{ ocp_thanos_receive_url.stdout }}/api/v1/receive"
            - "Add the THANOS_RECEIVE_URL=https://{{ ocp_thanos_receive_url.stdout }}/api/v1/receive to your .env file"
            