---
- name: Login to OpenShift Internal Registry
  shell: "docker login -u kubeadmin -p {{ ocp_token }} {{ ocp_internal_registry }}"
- name: Build leaderboard
  shell: "cd ../../services/leaderboard; DOCKER_BUILDKIT=0 docker buildx build --platform=linux/amd64 . -t {{ ocp_internal_registry }}/{{ ocp_project_name }}/leaderboard"
- name: Push leaderboard
  shell: "docker push {{ ocp_internal_registry }}/{{ ocp_project_name }}/leaderboard"
- name: Generate Leaderboard
  template:
    src: template/space-rover.yml
    dest: dest/space-rover.yml
- name: Create Leaderboard
  shell: "oc apply -f dest/space-rover.yml"