apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: mockrover
  name: mockrover
spec:
  type: LoadBalancer
  ports:
    - name: "5045"
      port: 5045
      targetPort: 5045
  selector:
    app.service: mockrover
status:
  loadBalancer: {}
