apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.service: prometheus
        app.name: space-rover
    spec:
      containers:
        - image: space-rover/prometheus:latest
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          # Change Pull Policy for Remote Registry
          imagePullPolicy: Never
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
      restartPolicy: Always
status: {}
