apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    # Physical path of PV Storage on your device running Kubernetes.
    # path: C:\data\mongo
    path: /opt/data/mongo